apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-java-springboot-basic-d7mo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-java-springboot-basic-d7mo
    app.kubernetes.io/part-of: devfile-sample-java-springboot-basic
  name: devfile-sample-java-springboot-basic-d7mo
spec:
  rules:
  - host: devfile-sample-java-springboot-basic-d7mo-rh-ee-sombaner-tenant.api-y00zljez-centralindia-aroapp-io:6443
    http:
      paths:
      - backend:
          service:
            name: devfile-sample-java-springboot-basic-d7mo
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
